# Generated by Django 5.0.14 on 2026-05-10 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_newslettersubscriber_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
